"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AppointmentProvider(str, Enum):
    r"""An enumeration."""
    GETLABS = 'getlabs'
    AXLEHEALTH = 'axlehealth'
