"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import phlebotomyareainfo as shared_phlebotomyareainfo
from dataclasses_json import Undefined, dataclass_json
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class AreaInfo:
    phlebotomy: shared_phlebotomyareainfo.PhlebotomyAreaInfo = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phlebotomy') }})
    zip_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('zip_code') }})
    

