"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .phlebotomyareainfo import PhlebotomyAreaInfo
from dataclasses_json import Undefined, dataclass_json
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AreaInfo:
    phlebotomy: PhlebotomyAreaInfo = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phlebotomy') }})
    zip_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('zip_code') }})
    

