"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .mealindbbase_clientfacingsource_ import MealInDBBaseClientFacingSource
from dataclasses_json import Undefined, dataclass_json
from typing import List
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ClientFacingMealResponse:
    meals: List[MealInDBBaseClientFacingSource] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('meals') }})
    

