"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .timeslot import TimeSlot
from dataclasses_json import Undefined, dataclass_json
from datetime import date
from typing import List
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DaySlots:
    date_: date = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date'), 'encoder': utils.dateisoformat(False), 'decoder': utils.datefromisoformat }})
    slots: List[TimeSlot] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('slots') }})
    

