"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import timeslot as shared_timeslot
from dataclasses_json import Undefined, dataclass_json
from datetime import date
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DaySlots:
    date_: date = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date'), 'encoder': utils.dateisoformat(False), 'decoder': utils.datefromisoformat }})
    slots: list[shared_timeslot.TimeSlot] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('slots') }})
    

