"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class DemoProviders(str, Enum):
    r"""An enumeration."""
    APPLE_HEALTH_KIT = 'apple_health_kit'
    FITBIT = 'fitbit'
    FREESTYLE_LIBRE = 'freestyle_libre'
    OURA = 'oura'
