"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class IngestibleTimeseriesResource(str, Enum):
    r"""An enumeration."""
    BLOOD_PRESSURE = 'blood_pressure'
    BLOOD_OXYGEN = 'blood_oxygen'
    GLUCOSE = 'glucose'
    HEARTRATE = 'heartrate'
    HEARTRATE_VARIABILITY = 'heartrate_variability'
    WATER = 'water'
    CAFFEINE = 'caffeine'
    MINDFULNESS_MINUTES = 'mindfulness_minutes'
