"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .biomarkerresult import BiomarkerResult
from .labresultsmetadata import LabResultsMetadata
from dataclasses_json import Undefined, dataclass_json
from typing import List, Union
from vital import utils


@dataclasses.dataclass
class LabResultsRawResults:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LabResultsRaw:
    metadata: LabResultsMetadata = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metadata') }})
    results: Union[List[BiomarkerResult], LabResultsRawResults] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('results') }})
    

