"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MarkerType(str, Enum):
    r"""An enumeration."""
    BIOMARKER = 'biomarker'
    PANEL = 'panel'
