"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OAuthProviders(str, Enum):
    r"""An enumeration."""
    OURA = 'oura'
    FITBIT = 'fitbit'
    GARMIN = 'garmin'
    STRAVA = 'strava'
    WAHOO = 'wahoo'
    IHEALTH = 'ihealth'
    WITHINGS = 'withings'
    GOOGLE_FIT = 'google_fit'
    DEXCOM_V3 = 'dexcom_v3'
    POLAR = 'polar'
    CRONOMETER = 'cronometer'
    OMRON = 'omron'
