"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .openloopresourceidtype import OpenLoopResourceIDType
from .openloopwebhooktype import OpenLoopWebhookType
from dataclasses_json import Undefined, dataclass_json
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OpenLoopEvent:
    event_type: OpenLoopWebhookType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('event_type') }})
    r"""An enumeration."""
    resource_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_id') }})
    resource_id_type: OpenLoopResourceIDType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_id_type') }})
    r"""An enumeration."""
    

