"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OpenLoopResourceIDType(str, Enum):
    r"""An enumeration."""
    APPOINTMENT = 'Appointment'
    FORM_ANSWER_GROUP = 'FormAnswerGroup'
    ENTRY = 'Entry'
    NOTE = 'Note'
