"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import openloopresourceidtype as shared_openloopresourceidtype
from ..shared import openloopwebhooktype as shared_openloopwebhooktype
from dataclasses_json import Undefined, dataclass_json
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OpenLoopEvent:
    event_type: shared_openloopwebhooktype.OpenLoopWebhookType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('event_type') }})
    r"""An enumeration."""
    resource_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_id') }})
    resource_id_type: shared_openloopresourceidtype.OpenLoopResourceIDType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_id_type') }})
    r"""An enumeration."""
    

