"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OrderTopLevelStatus(str, Enum):
    r"""An enumeration."""
    RECEIVED = 'received'
    COLLECTING_SAMPLE = 'collecting_sample'
    SAMPLE_WITH_LAB = 'sample_with_lab'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    FAILED = 'failed'
