"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PasswordProviders(str, Enum):
    r"""An enumeration."""
    WHOOP = 'whoop'
    RENPHO = 'renpho'
    PELOTON = 'peloton'
    ZWIFT = 'zwift'
    EIGHT_SLEEP = 'eight_sleep'
    BEURER_API = 'beurer_api'
    DEXCOM = 'dexcom'
    HAMMERHEAD = 'hammerhead'
    MY_FITNESS_PAL = 'my_fitness_pal'
