"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PayorSearchRequest:
    insurance_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('insurance_name') }})
    insurance_state: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('insurance_state'), 'exclude': lambda f: f is None }})
    

