"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Region(str, Enum):
    r"""An enumeration."""
    US = 'us'
    EU = 'eu'
    SG = 'sg'
    DE = 'de'
    AU = 'au'
    BR = 'br'
    NL = 'nl'
    FR = 'fr'
