"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ResultType(str, Enum):
    r"""An enumeration."""
    NUMERIC = 'numeric'
    RANGE = 'range'
    COMMENT = 'comment'
