"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import region as shared_region
from ..shared import vitaltokenexchangeteamresponse as shared_vitaltokenexchangeteamresponse
from dataclasses_json import Undefined, dataclass_json
from vital import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class VitalTokenExchangeResponse:
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    environment: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('environment') }})
    region: shared_region.Region = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('region') }})
    r"""An enumeration."""
    team: shared_vitaltokenexchangeteamresponse.VitalTokenExchangeTeamResponse = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('team') }})
    user_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user_id') }})
    

