"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class CheckTokenValidV2LinkTokenIsValidPostResponseCheckTokenValidV2LinkTokenIsvalidPost:
    r"""Successful Response"""
    



@dataclasses.dataclass
class CheckTokenValidV2LinkTokenIsValidPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    response_check_token_valid_v2_link_token_isvalid_post: Optional[CheckTokenValidV2LinkTokenIsValidPostResponseCheckTokenValidV2LinkTokenIsvalidPost] = dataclasses.field(default=None)
    r"""Successful Response"""
    

