"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import connectionstatus as shared_connectionstatus
from typing import Optional


@dataclasses.dataclass
class ConnectEmailAuthV2LinkAuthEmailPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    connection_status: Optional[shared_connectionstatus.ConnectionStatus] = dataclasses.field(default=None)
    r"""Successful Response"""
    

