"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from ...models.shared import vitaltokencreatedresponse as shared_vitaltokencreatedresponse
from datetime import datetime
from typing import Optional


@dataclasses.dataclass
class CreateTokenV2LinkCodeCreatePostRequest:
    user_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'user_id', 'style': 'form', 'explode': True }})
    expires_at: Optional[datetime] = dataclasses.field(default=dateutil.parser.isoparse('2023-10-11T13:41:29.554841+00:00'), metadata={'query_param': { 'field_name': 'expires_at', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class CreateTokenV2LinkCodeCreatePostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    vital_token_created_response: Optional[shared_vitaltokencreatedresponse.VitalTokenCreatedResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

