"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import usersuccessresponse as shared_usersuccessresponse
from typing import Optional



@dataclasses.dataclass
class DeleteUserV2UserUserIDDeleteRequest:
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class DeleteUserV2UserUserIDDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    user_success_response: Optional[shared_usersuccessresponse.UserSuccessResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

