"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import providers as shared_providers
from ...models.shared import usersuccessresponse as shared_usersuccessresponse
from typing import Optional


@dataclasses.dataclass
class DeregisterProviderV2UserUserIDProviderDeleteRequest:
    provider: shared_providers.Providers = dataclasses.field(metadata={'path_param': { 'field_name': 'provider', 'style': 'simple', 'explode': False }})
    r"""Provider slug. e.g., `oura`, `fitbit`, `garmin`."""
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class DeregisterProviderV2UserUserIDProviderDeleteResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    user_success_response: Optional[shared_usersuccessresponse.UserSuccessResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

