"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import linktokenexchangeresponse as shared_linktokenexchangeresponse
from typing import Optional


@dataclasses.dataclass
class GenerateVitalLinkTokenV2LinkTokenPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    link_token_exchange_response: Optional[shared_linktokenexchangeresponse.LinkTokenExchangeResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

