"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import clientfacinguser as shared_clientfacinguser
from typing import Optional


@dataclasses.dataclass
class GetUserV2UserUserIDGetRequest:
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetUserV2UserUserIDGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    client_facing_user: Optional[shared_clientfacinguser.ClientFacingUser] = dataclasses.field(default=None)
    r"""Successful Response"""
    

