"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import oauthproviders as shared_oauthproviders
from ..shared import source as shared_source
from typing import Optional



@dataclasses.dataclass
class GetOauthProviderV2LinkProviderOauthOauthProviderGetRequest:
    oauth_provider: shared_oauthproviders.OAuthProviders = dataclasses.field(metadata={'path_param': { 'field_name': 'oauth_provider', 'style': 'simple', 'explode': False }})
    r"""An enumeration."""
    




@dataclasses.dataclass
class GetOauthProviderV2LinkProviderOauthOauthProviderGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    source: Optional[shared_source.Source] = dataclasses.field(default=None)
    r"""Successful Response"""
    

