"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import clientfacingsleepstream as shared_clientfacingsleepstream
from typing import Optional


@dataclasses.dataclass
class GetUserSleepStreamV2TimeseriesSleepSleepIDStreamGetRequest:
    sleep_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'sleep_id', 'style': 'simple', 'explode': False }})
    r"""The Vital Sleep ID"""
    



@dataclasses.dataclass
class GetUserSleepStreamV2TimeseriesSleepSleepIDStreamGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    client_facing_sleep_stream: Optional[shared_clientfacingsleepstream.ClientFacingSleepStream] = dataclasses.field(default=None)
    r"""Successful Response"""
    

