"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import clientfacingmarker as shared_clientfacingmarker
from typing import Optional


@dataclasses.dataclass
class GetMarkersByProviderIDV3LabTestsLabIDMarkersProviderIDGetRequest:
    lab_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'lab_id', 'style': 'simple', 'explode': False }})
    provider_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'provider_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetMarkersByProviderIDV3LabTestsLabIDMarkersProviderIDGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    client_facing_marker: Optional[shared_clientfacingmarker.ClientFacingMarker] = dataclasses.field(default=None)
    r"""Successful Response"""
    

