"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientfacingproviderwithstatus as shared_clientfacingproviderwithstatus
from typing import Dict, List, Optional


@dataclasses.dataclass
class GetConnectedProvidersV2UserProvidersUserIDGetRequest:
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetConnectedProvidersV2UserProvidersUserIDGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    response_get_connected_providers_v2_user_providers_user_id_get: Optional[Dict[str, List[shared_clientfacingproviderwithstatus.ClientFacingProviderWithStatus]]] = dataclasses.field(default=None)
    r"""Successful Response"""
    

