"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class GetSvixWebhookURLV2TeamSvixURLGetResponseGetSvixWebhookURLV2TeamSvixURLGet:
    r"""Successful Response"""
    



@dataclasses.dataclass
class GetSvixWebhookURLV2TeamSvixURLGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    response_get_svix_webhook_url_v2_team_svix_url_get: Optional[GetSvixWebhookURLV2TeamSvixURLGetResponseGetSvixWebhookURLV2TeamSvixURLGet] = dataclasses.field(default=None)
    r"""Successful Response"""
    

