"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import userrefreshsuccessresponse as shared_userrefreshsuccessresponse
from typing import Optional


@dataclasses.dataclass
class RefreshUserIDV2UserRefreshUserIDPostRequest:
    user_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class RefreshUserIDV2UserRefreshUserIDPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    user_refresh_success_response: Optional[shared_userrefreshsuccessresponse.UserRefreshSuccessResponse] = dataclasses.field(default=None)
    r"""Successful Response"""
    

