"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientfacingpayorsearchresponse as shared_clientfacingpayorsearchresponse
from typing import Optional



@dataclasses.dataclass
class SearchInsurancePayorInformationV3InsuranceSearchPayorPostResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    client_facing_payor_search_responses: Optional[list[shared_clientfacingpayorsearchresponse.ClientFacingPayorSearchResponse]] = dataclasses.field(default=None)
    r"""Successful Response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

