"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import List, Optional


@dataclasses.dataclass
class UpdateSourcePrioritiesV2TeamSourcePrioritiesPatchRequest:
    team_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'team_id', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class UpdateSourcePrioritiesV2TeamSourcePrioritiesPatchResponseBody:
    pass


@dataclasses.dataclass
class UpdateSourcePrioritiesV2TeamSourcePrioritiesPatchResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    response_update_source_priorities_v2_team_source_priorities_patch: Optional[List[UpdateSourcePrioritiesV2TeamSourcePrioritiesPatchResponseBody]] = dataclasses.field(default=None)
    r"""Successful Response"""
    

